### ISSUE TITLE
HEREDOC parsing broken?

### ISSUE THREAD

**Issue by jbellsey** [dmarcotte/idea-handlebars#102]
When this plugin is enabled, normal HTML parsing inside a HEREDOC is broken. E.g.:

```PHP
<?php
echo <<< HTML
   <div></div>
HTML;
```

The special HEREDOC symbol "HTML" tells PHPStorm to treat the doc specially, what with syntax highlighting, code completion, etc. 

With this plugin enabled, the parsing is broken, leaving the text uncolored and without any assists, as it is when using generic HEREDOC symbols (e.g., `echo <<< EOT`).

Thoughts?

**Comment by dmarcotte** [comment]
Thanks @jbellsey.  Really appreciate you reaching out, and hope the plugin's been handy.

This sounds like an issue for sure, or a feature request at the very least, though I don't have the visibility into PHPStorm internals required to properly troubleshoot... definitely worth [filing with Jetbrains](https://youtrack.jetbrains.com/issues/WEB).

Going to close this, but it you could drop a link to the YouTrack issue here after you file it, that would be great.

**Comment by jbellsey** [comment]
Thanks Daniel. Just filed with JB here:
https://youtrack.jetbrains.com/issue/WI-26542
