### ISSUE TITLE
HTMLBars support

### ISSUE THREAD

**Issue by Tonkonozhenko** [dmarcotte/idea-handlebars#104]
Hello!

What about HTMLBars from Ember?
Will you support features from it?
E.g. now they have block params (http://emberjs.com/blog/2015/02/07/ember-1-10-0-released.html#toc_block-params)
```handlebars
{{currentUser.name}}
{{#each cars as |car|}}
  {{#with car.manufacturer as |make|}}
    {{make.name}}
    {{currentUser.name}} 
  {{/with}}
{{/each}}
```

**Comment by aceofspades** [comment]
This is actually handlebars 3.0 syntax.

**Comment by dmarcotte** [comment]
Thanks @Tonkonozhenko, @aceofspades.  Will hopefully get this in soon...

Also: closing this in favor of https://youtrack.jetbrains.com/issue/WEB-15893
