### ISSUE TITLE
Don't work properly with filename "timeline.hbs"

### ISSUE THREAD

**Issue by Orthocenter** [dmarcotte/idea-handlebars#107]
When I created a file named "timeline.hbs", this plugin seemed not to handle this file. After that, I also tried "timeline2.hbs", it worked well this time~

**Comment by dmarcotte** [comment]
@Orthocenter, it sounds like you have mapped `timeline.hbs` to another file type in `Preferences->Editor->File Types`.  That would result in the behavior you're seeing.

**Comment by Orthocenter** [comment]
@dmarcotte thx! It works now. But I don't remember when I mapped it into text type..

**Comment by dmarcotte** [comment]
Great!  As for mapping to text: it may have happened automatically if you opened the file before installing the plugin.

**Comment by Orthocenter** [comment]
@dmarcotte thanks a lot for your explanation : )
