### ISSUE TITLE
Still not support handlebars 3 block parameter

### ISSUE THREAD

**Issue by palamike** [dmarcotte/idea-handlebars#108]
This syntax still not support in PHPStorm

{{#each errors as |error error_field| }}
{{/each}}

It will hilight error at the "|" and says "expected close }}" 

please help to consider

**Comment by cubesun** [comment]
+1

**Comment by dmarcotte** [comment]
This should now be working in all IDEA 14 and 15EAP era IDEs (build numbers of 141.1 to 143).  IDEA 14 support was just released and will show up in repos soon.
