### ISSUE TITLE
No longer working after updating to PHPStorm 9

### ISSUE THREAD

**Issue by kim-mettro** [dmarcotte/idea-handlebars#110]
I have this plugin installed and was working perfectly in PHPStorm 8.

I just updated to PHPStorm 9 and it no longer appears to be working. When I open a .hbs file I am prompted to install a plugin even though I have this plugin installed. There is no syntax highlighting on hbs files.

**Comment by dmarcotte** [comment]
Hey @kim-mettro, apologies I didn't see this sooner.  It sounds like you need to update the plugin.  In `Preferences-Plugins`, right-click "Handlebars/Mustache" and choose "Reload list of plugins", the right-click it again and choose "Update Plugin".

Going to optimistically close this, but please let me know if that doesn't resolve things and we'll dig deeper.

**Comment by kim-mettro** [comment]
Hi Daniel

I swear I tried updating the plugin when I had the problem, but I had
another look at it when I got your email and now it's working. Thanks very
much for getting back to me.

Kim



Kind regards,

Kim Ulrick  |  MeTTro
-----------------------------------------------------|
85 Lewis Street, Woolloongabba Qld 4102
Tel 07 3334 8320 | Fax 3895 8920

**Comment by dmarcotte** [comment]
Fantastic.  Glad that worked out.
