### ISSUE TITLE
Not compatible with PHPStorm 9.0.2

### ISSUE THREAD

**Issue by WanielDeiss** [dmarcotte/idea-handlebars#112]
i can't use the plugin with PHPStrom 9.0.2 :cry: 

Error: Plugin is incompatible with this installation.

**Comment by anstarovoyt** [comment]
Could you please attach a screenshot with the plugin in 'plugins' preferences?

**Comment by dmarcotte** [comment]
@WanielDeiss going to close this since we were unable to reproduce, but if you're still stuck, please post the screenshot @anstarovoyt asked for and we'll do everything we can to get you up and running.
