### ISSUE TITLE
When using expressions, the plugin marks them as errors

### ISSUE THREAD

**Issue by shal1y** [dmarcotte/idea-handlebars#115]
When using expressions in .hbs or .mustache files, the editor marks the expressions with error. See image below:

![screen shot 2015-12-03 at 10 55 19 am](https://cloud.githubusercontent.com/assets/6255377/11570496/62e2bb4a-99ac-11e5-9bb5-84422dedb015.png)

**Comment by dmarcotte** [comment]
Hey @shal1y, I believe this is indeed an error.  Brackets go around the helper and its arguments in sub-expressions.  Try `{{#if (isSeriesSelectionType @index)}}`.

Hope that helps (please let me know if I've missed something here!), and hope the plugin is treating you well.
