### ISSUE TITLE
HBSv4.0.5 new partial syntax

### ISSUE THREAD

**Issue by JetAlex** [dmarcotte/idea-handlebars#116]
Hello
http://handlebarsjs.com/partials.html
WebStorm doesnt understand several new constructions like: 
{{#*inline "myPartial"}}
...
{{/inline}}
and 
{{#> layout}}
...
Is it possible to add support for these tags?

**Comment by dmarcotte** [comment]
Hey, thanks for the heads up @JetAlex.  Closing this as a dupe of https://youtrack.jetbrains.com/issue/WEB-19497, but rest assured this is going to get some attention soon.
