### ISSUE TITLE
After installing the plugin in IntelliJ IDEA, it is not possible to preview html files in browsers any more

### ISSUE THREAD

**Issue by palmo108** [dmarcotte/idea-handlebars#117]
Hi,
after installing the plugin all html5 files now have the icon with mustache and it is not possible to view them in any web browser. In the file type settings the *.html files are still associated with HTML. 

When the plugin is switched off, this behaviour disappears. 

I use IntelliJ 15.03 Ultimate. 

Karolina

**Comment by dmarcotte** [comment]
Hi @palmo108,

Sounds like you have "Open HTML files as Handlebars/Mustache" checked.  Unchecking it should stop handling all your html files with this plugin.

(Optimistically closing this, but let me know if that doesn't fix you up!  We'll reopen and try something else).
