### ISSUE TITLE
Paths to .hbs files not recognized/navigatable

### ISSUE THREAD

**Issue by bjoern-dev** [dmarcotte/idea-handlebars#128]
Hi there,

awesome plugin - thanks for your hard work.
We are experiencing problems with source ode navigation in IDEA: whenever there are partials/templates included with {{> some/path/to/file }} , we can not jump to that file with CMD+click - it says "Cannot find declaration to go to". 
This makes it really tiring to work with multiple files.
Any help on this one would be appreciated.

Thanks and cheers!

**Comment by dmarcotte** [comment]
Hi @bjoern-dev, really glad you're benefiting from the plugin!  I understand your pain with the lack of jump-to on those file references.  As this plugin is now maintained by Jetbrains, your best bet to get some traction here is to file an issue here: http://youtrack.jetbrains.com/issues/WEB

You should likely upvote this related issue too as resolving helpers is technically related to resolving file paths: https://youtrack.jetbrains.com/issue/WEB-14315

Hope that helps, and thanks again!

**Comment by bjoern-dev** [comment]
Thank @dmarcotte, I created https://youtrack.jetbrains.com/issue/WEB-29381 glad for any votes from anyone who sees this and thinks it's useful.
Cheers
