### ISSUE TITLE
Great plugin! Can for nunjucks template language to make a plugin?

### ISSUE THREAD

**Issue by leftstyle** [dmarcotte/idea-handlebars#129]
thx.

**Comment by dmarcotte** [comment]
Thanks @leftstyle!  Glad you like it.

I can't take on another plugin in the foreseeable future, but the code here (and even more so the newer version in https://github.com/JetBrains/intellij-plugins/tree/master/handlebars) should provide a ton of guidance that someone should be able to use to implement their own template language plugins.  Starting with a highlighter and building up from there is probably the best way to break down the problem.

Hope that helps a bit, and thanks again.
