### ISSUE TITLE
Not working after Update 2018.1

### ISSUE THREAD

**Issue by maikkel** [dmarcotte/idea-handlebars#130]
After the 2018.1 Update for PHPStorm, .hbs files are not recognised. The Plugin is installed, but the filetype isn't listed under File Types in Settings... switched .hbs to html for the time being.

**Comment by chrismou** [comment]
I've logged the issue on the jetbrains issue tracker: https://youtrack.jetbrains.com/issue/WEB-32121

**Comment by norbertas-gaulia** [comment]
ticket upvoted

**Comment by dmarcotte** [comment]
Looks like there's now a workaround noted in https://youtrack.jetbrains.com/issue/WEB-32121 (thanks for filing that @chrismou): **uninstall and re-install the plugin should get things going**.  Not sure why it's not automatically updated, but I expect the fine folks at Jetbrains have their eye on that.
