### ISSUE TITLE
Using this plugin with *.php.mustache files

### ISSUE THREAD

**Issue by milansimek** [dmarcotte/idea-handlebars#131]
Hi, first of all I'd like to say that this is a great plugin!

I'm just running into an issue where I can't seem to get the plugin to work correctly with *.php.mustache files. The fallback syntax highlighting is HTML instead of PHP.

I have no problems with the plugin when editing HTML or XML files though.

Any ideas how I can make it work with php file templates?

**Comment by dmarcotte** [comment]
Hi @milansimek, unfortunately this is a long-known issue.  Upvote this issue to hopefully encourage support: https://youtrack.jetbrains.com/issue/IDEA-106449

Your best option in the meantime (which I acknowledge is not great, and may not even be possible) would be reorganize your project so that your templates are not embedded in your php.

**Comment by milansimek** [comment]
Hi @dmarcotte, 

I'm working on a product related to generating / scaffolding PHP code. So I'm using Mustache inside several .php file templates, which in turn generate PHP files.

Is there anyway to set the 'parent' language to PHP? I noticed you can change the template data language, but PHP is missing there. If I set the template data language to Javascript at least indenting works sort of, but it's still not a proper solution.

I'm familiar with Java and have no problem with doing some edits and compiling the plugin. Just wondering if it's something that can be (relatively easily) done, and which files would be relevant for this change. That way I can maybe modify the plugin to make it work for my specific purpose.

It seems the plugin inherits / extends on the HTML syntax / code style, would it be possible to change this to PHP some way? 

Thanks!

**Comment by milansimek** [comment]
@dmarcotte any ideas?

Thanks!

**Comment by milansimek** [comment]
@dmarcotte that's a shame.. I'll just use the Javascript workaround for now then.

Thanks anyway! I'll upvote the issue you mentioned, let's hope it get's picked up soon.
