### ISSUE TITLE
Cannot open file in ISO-8859-1

### ISSUE THREAD

**Issue by catja77** [dmarcotte/idea-handlebars#135]
I am not sure if this is a problem in the plugin or a intellij issue but I am no able to open a .hbs file in ISO-8859-1 encoding. This seems to have been a problem with the later versions. When I open the file I get a message that the file was opened in the wrong encoding (UTF-8) but when I choose the correct encoding and chooses to reload the file it will again just state it is the wrong encoding (UTF-8).
<img width="1145" alt="Screenshot 2021-11-16 at 22 58 38" src="https://user-images.githubusercontent.com/67102750/142073232-11751dab-709a-4aff-a1c3-eed86354ad95.png">
<img width="1267" alt="Screenshot 2021-11-16 at 22 58 20" src="https://user-images.githubusercontent.com/67102750/142073235-d7c66f06-8a2d-4d75-aa6c-0bdd4fc7e3b3.png">

**Comment by dmarcotte** [comment]
Hi @catja77, glad you're getting use out of the plugin, and sorry to hear that you're running into an issue.  Jetbrains took over maintenance of this plugin quite a while ago, so your best bet to get some help here is to file an issue at https://youtrack.jetbrains.com/issues/IDEA
